version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: online_store
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: online_store
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
